#!/bin/bash

if [ "$1" == "kafka" ]; then
    /home/brumen/archive/software/kafka/start_kafka &
    /home/brumen/archive/software/kafka/start_kafka_connect &

elif [ "$1" == "trade_service" ]; then
    python /home/brumen/work/rm/services/ao/trade_service.py

elif [ "$1" == "market_service" ]; then
    python /home/brumen/work/rm

elif [ "$1" == "trade_api" ]; then
    python /home/brumen/work/rm/services/ao/trade_api.py

elif [ "$1" == "trade_api_multi" ]; then
    gunicorn -w 8 trade_api::application


elif [ "$1" == "all" ]; then  # do all in separate terminals
    xterm -hold -e "python /home/brumen/work/rm/services/ao/trade_service.py" &

fi
