kafka_server_name: "localhost"
kafka_server_port: 9092
mkt_topic: "mkt_events"
results_topic: "air_options.ao.results"
pos_topic: "air_options.ao.option_positions"
trade_pricer: "localhost:5010"
pricing_params:
    nb_sim: 5000
    default_price: 200.
metric: "PV"