#! /bin/bash

# KAFKA system part:
# first you have the kafka system & zookeeper up and running
#    go to folder: ~/archive/software/kafka...
#    start ./bin/zookeeper-server-start.sh config/zooker-properties
#    start ./bin/kafka-server-start.sh config/server-properties
# kafka connect:
#     start ./start_kafka_connect
#     this writes on the topic demo.ao.option_positions and reports the option_positions

# PYTHON PART:
#    start market updater in python:
#           from rm.market_ticker import MarketUpdaterJoke; mu = MarketUpdaterJoke(); mu.start(idle_delay=5)
#    start controller:
#           from rm.controller_ao2 import ControllerAO; ao = ControllerAO(); ao.start()

#    start result publisher:
#        python result_publisher.py

#    react code in:
#       ~/learn/counter-app/app.js


# POSITION UPDATER IS NOT NEEDED ANYMORE:
#    start position updater in python:
#           from rm.positions_updater import PositionUpdaterJoke; pu = PositionUpdaterJoke(); pu.start(idle_delay=0.1)
