#! /bin/bash

# KAFKA system part:
# first you have the kafka system & zookeeper up and running
#    go to folder: ~/archive/software/kafka...
#    start ./bin/zookeeper-server-start.sh config/zooker-properties
#    start ./bin/kafka-server-start.sh config/server-properties
# kafka connect:
#     start ./start_kafka_connect
#     this writes on the topic demo.ao.option_positions and reports the option_positions

# PYTHON PART:
#    start market service in python:
#           python3.9 services/market_service_start.py
#    start controller (results) service:
#           python3.9 services/controller_ao2_start.py
#    start result publisher:
#        python3.9 services/result_publisher.py


# POSITION UPDATER IS NOT NEEDED ANYMORE:
#    start position updater in python:
#           from rm.positions_updater import PositionUpdaterJoke; pu = PositionUpdaterJoke(); pu.start(idle_delay=0.1)
