#!/bin/bash

server_name="192.168.1.107"
kafka_console_cmd="/home/brumen/archive/software/kafka/kafka-3.4.0-src/bin/kafka-console-consumer.sh "
server="--bootstrap-server $server_name:9092 "

if [ "$1" == "monitors" ]; then
    gnome-terminal --tab -- $kafka_console_cmd $server --topic letf.mkt
    gnome-terminal --tab -- $kafka_console_cmd $server --topic letf.positions
    gnome-terminal --tab -- $kafka_console_cmd $server --topic letf.results
    gnome-terminal --tab -- $kafka_console_cmd $server --topic letf.risk

elif [ "$1" == "kafka" ]; then
    gnome-terminal --tab -- /home/brumen/archive/software/kafka/start_kafka
    # gnome-terminal --tab -- /home/brumen/archive/software/kafka/start_kafka_connect

    # only trade service is needed. Pricer is done in the controller, and
    # market thread is part of the letf_trade_service
elif [ "$1" == "services" ]; then
    # gnome-terminal --tab -- /home/brumen/archive/software/kafka/start_kafka
    # gnome-terminal --tab -- /home/brumen/archive/software/kafka/start_kafka_connect
    gnome-terminal --tab -- python /home/brumen/work/rm/services/letf/letf_trade_service.py
    # python /home/brumen/work/rm/services/letf/letf_trade_service.py
    # gnome-terminal --tab -- python /home/brumen/work/rm/services/letf/letf_market_service.py
fi
